import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'
import { optimize, type PluginConfig } from 'svgo'
import {
  iconSources,
  type IconKind,
  type IconSourceConfig,
} from './config'
import { toComponentName } from './naming'

export interface PreviewManifestItem {
  iconfontName: string
  componentName: string
  kind: IconKind
}

export function assertUniqueComponentNames(
  componentNames: string[],
  kind: IconKind,
): void {
  const seen = new Set<string>()

  for (const componentName of componentNames) {
    if (seen.has(componentName)) {
      throw new Error(`Found duplicate ${kind} component name: ${componentName}`)
    }

    seen.add(componentName)
  }
}

export function renderIndexSource(
  outlinedComponents: string[],
  coloredComponents: string[],
): string {
  const lines = [
    '// This file is auto-generated by scripts/build.ts.',
    "export type { BaseIconProps, ColoredIconProps, OutlinedIconProps } from './shared/IconBase'",
    '',
  ]

  for (const componentName of [...outlinedComponents].sort()) {
    lines.push(
      `export { default as ${componentName} } from './components/outlined/${componentName}'`,
    )
  }

  if (outlinedComponents.length > 0 && coloredComponents.length > 0) {
    lines.push('')
  }

  for (const componentName of [...coloredComponents].sort()) {
    lines.push(
      `export { default as ${componentName} } from './components/colored/${componentName}'`,
    )
  }

  return `${lines.join('\n')}\n`
}

export function renderPreviewManifestSource(items: PreviewManifestItem[]): string {
  const manifestItems = items
    .map(
      (item) =>
        `  { iconfontName: '${item.iconfontName}', componentName: '${item.componentName}', kind: '${item.kind}' },`,
    )
    .join('\n')

  return `// This file is auto-generated by scripts/build.ts.
export interface PreviewManifestItem {
  iconfontName: string
  componentName: string
  kind: 'outlined' | 'colored'
}

export const previewManifest: PreviewManifestItem[] = [
${manifestItems}
]
`
}

export function toCopySnippet(componentName: string): string {
  return `<${componentName} />`
}

export function resolveUniqueComponentName(
  componentName: string,
  suffix: string,
  usedNames: Set<string>,
): string {
  let candidate = componentName
  let counter = 2
  const suffixIndex = componentName.endsWith(suffix)
    ? componentName.length - suffix.length
    : componentName.length
  const baseName = componentName.slice(0, suffixIndex)

  while (usedNames.has(candidate.toLowerCase())) {
    candidate = `${baseName}${counter}${suffix}`
    counter += 1
  }

  usedNames.add(candidate.toLowerCase())
  return candidate
}

function optimizeSvg(svg: string, kind: IconKind): string {
  const plugins: PluginConfig[] = ['preset-default', 'removeDimensions']

  if (kind === 'outlined') {
    plugins.push({
      name: 'convertColors',
      params: { currentColor: true },
    })
  }

  const result = optimize(svg, {
    plugins,
  })

  return result.data
}

function extractInnerSvg(svg: string): { viewBox: string; content: string } {
  const viewBoxMatch = svg.match(/viewBox="([^"]+)"/)
  const innerMatch = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)

  if (!innerMatch) {
    throw new Error('Failed to extract SVG body for component generation')
  }

  return {
    viewBox: viewBoxMatch?.[1] ?? '0 0 1024 1024',
    content: innerMatch[1].trim(),
  }
}

function renderComponentSource(
  componentName: string,
  kind: IconKind,
  svg: string,
): string {
  const { viewBox, content } = extractInnerSvg(svg)
  const propsType = kind === 'outlined' ? 'OutlinedIconProps' : 'ColoredIconProps'

  return `import React from 'react'
import { IconBase } from '../../shared/IconBase'
import type { ${propsType} } from '../../shared/IconBase'

const svgContent = ${JSON.stringify(content)}

export default function ${componentName}(props: ${propsType}) {
  return (
    <IconBase
      {...props}
      kind="${kind}"
      viewBox="${viewBox}"
      content={svgContent}
    />
  )
}
`
}

export function generateComponentSource(
  componentName: string,
  kind: IconKind,
  svg: string,
): string {
  return renderComponentSource(componentName, kind, svg)
}

export interface BuildIconSourceResult {
  componentNames: string[]
  previewItems: PreviewManifestItem[]
}

export function buildIconSource(
  source: IconSourceConfig,
  rootDir = process.cwd(),
): BuildIconSourceResult {
  const inputDir = path.resolve(rootDir, source.rawDir)
  const outputDir = path.resolve(rootDir, source.componentDir)

  if (!fs.existsSync(inputDir)) {
    throw new Error(`Missing raw SVG directory: ${source.rawDir}`)
  }

  fs.rmSync(outputDir, { recursive: true, force: true })
  fs.mkdirSync(outputDir, { recursive: true })

  const componentNames: string[] = []
  const previewItems: PreviewManifestItem[] = []
  const usedComponentNames = new Set<string>()
  const files = fs
    .readdirSync(inputDir)
    .filter((file) => file.endsWith('.svg'))
    .sort((left, right) => left.localeCompare(right))

  for (const fileName of files) {
    const iconId = fileName.replace(/\.svg$/i, '')
    const componentName = resolveUniqueComponentName(
      toComponentName(iconId, source.suffix),
      source.suffix,
      usedComponentNames,
    )
    const svg = fs.readFileSync(path.join(inputDir, fileName), 'utf8')
    const componentSource = generateComponentSource(
      componentName,
      source.kind,
      optimizeSvg(svg, source.kind),
    )

    componentNames.push(componentName)
    previewItems.push({
      iconfontName: iconId,
      componentName,
      kind: source.kind,
    })
    const targetFileName = `${componentName}.tsx`
    const targetPath = path.join(outputDir, targetFileName)
    // Windows 文件系统大小写不敏感：若已存在仅大小写不同的旧文件（如 AfColored.tsx），
    // 直接写入 AFColored.tsx 可能不会更新文件名。先删除旧文件再写入，确保文件名正确。
    const existing = fs.readdirSync(outputDir).find(
      (f) => f.toLowerCase() === targetFileName.toLowerCase() && f !== targetFileName,
    )
    if (existing) {
      fs.unlinkSync(path.join(outputDir, existing))
    }
    fs.writeFileSync(targetPath, componentSource, 'utf8')
  }

  assertUniqueComponentNames(componentNames, source.kind)

  return { componentNames, previewItems }
}

export function writeIndexSource(
  outlinedComponents: string[],
  coloredComponents: string[],
  rootDir = process.cwd(),
): void {
  const indexPath = path.resolve(rootDir, 'src/index.ts')
  fs.writeFileSync(
    indexPath,
    renderIndexSource(outlinedComponents, coloredComponents),
    'utf8',
  )
}

export function writePreviewManifestSource(
  items: PreviewManifestItem[],
  rootDir = process.cwd(),
): void {
  const manifestPath = path.resolve(rootDir, 'src/preview-manifest.ts')
  fs.writeFileSync(manifestPath, renderPreviewManifestSource(items), 'utf8')
}

export function runBuild(rootDir = process.cwd()): void {
  const outlinedBuild =
    buildIconSource(iconSources.find((source) => source.kind === 'outlined')!, rootDir)
  const coloredBuild =
    buildIconSource(iconSources.find((source) => source.kind === 'colored')!, rootDir)

  writeIndexSource(outlinedBuild.componentNames, coloredBuild.componentNames, rootDir)
  writePreviewManifestSource(
    [...outlinedBuild.previewItems, ...coloredBuild.previewItems],
    rootDir,
  )
}

const isDirectExecution =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href

if (isDirectExecution) {
  try {
    runBuild()
  } catch (error) {
    console.error(error)
    process.exit(1)
  }
}
