apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: {{ .Values.studio.nodeEnv | quote }}
  OPENCLAW_ROOT_DIR: {{ .Values.studio.OpenClawRootDir | quote }}
  KWEAVER_BASE_URL: {{ .Values.studio.KWeaverBaseURL | quote }}
  KWEAVER_HYDRA_ADMIN_URL: {{ .Values.studio.KWeaverHydraAdminURL | quote }}
