apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels.deployment | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels.pod | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- toYaml .Values.labels.pod | nindent 8 }}
    spec:
      volumes:
        - name: OpenClawRootDir
          hostPath:
            path: {{ .Values.studio.OpenClawRootDir }}
            type: DirectoryOrCreate
        - name: envFilePath
          hostPath:
            path: {{ .Values.studio.envFilePath }}
            type: FileOrCreate
      containers:
        - name: dip-studio
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: studio-http
              protocol: TCP
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: NODE_ENV
            - name: OPENCLAW_ROOT_DIR
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: OPENCLAW_ROOT_DIR
            - name: KWEAVER_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: KWEAVER_BASE_URL
            - name: KWEAVER_HYDRA_ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: KWEAVER_HYDRA_ADMIN_URL
          resources:
            {{- toYaml .Values.resources.studio | nindent 12 }}
          volumeMounts:
            - name: OpenClawRootDir
              mountPath: /root/.openclaw
            - name: envFilePath
              mountPath: /app/.env
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
