apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  OPENCLAW_GATEWAY_TOKEN: {{ .Values.studio.openclaw.gatewayToken | quote }}
