export const PROMPT_LIST = [
  {
    name: '内置提示词',
    id: '000100000000',
    type: 'folder',
    is_build_in: true,
    children: [
      {
        name: 'chat',
        id: '000100010000',
        type: 'folder',
        children: [
          { name: '担任面试官', id: '000100010001', type: 'document' },
          { name: '代码解释器', id: '000100010002', type: 'document' },
          { name: '会议纪要', id: '000100010003', type: 'document' },
          { name: '新闻内容撰写', id: '000100010004', type: 'document' },
          { name: '项目计划书撰写', id: '000100010005', type: 'document' },
          { name: '自动生成代码', id: '000100010006', type: 'document' },
          { name: '有话题诗词', id: '000100010007', type: 'document' },
        ],
      },
      {
        name: 'completion',
        id: '000100020000',
        type: 'folder',
        children: [
          { name: '阅读理解', id: '000100020001', type: 'document' },
          { name: '相关问题推荐', id: '000100020002', type: 'document' },
          { name: '文档摘要', id: '000100020003', type: 'document' },
          { name: '文档 Q&A', id: '000100020004', type: 'document' },
          { name: 'subgraph答案整合', id: '000100020005', type: 'document' },
          { name: '废止政策信息抽取', id: '000100020006', type: 'document' },
          { name: '意图分类', id: '000100020007', type: 'document' },
          { name: '根据查询结果回答问题（QA）', id: '000100020008', type: 'document' },
          { name: '企业违规信息抽取', id: '000100020009', type: 'document' },
          { name: '政策变更信息抽取', id: '000100020010', type: 'document' },
          { name: 'Text2SQL和SQL解释', id: '000100020011', type: 'document' },
          { name: '用户意图判断', id: '000100020012', type: 'document' },
          { name: '槽位填充/意图识别', id: '000100020013', type: 'document' },
          { name: '翻译', id: '000100020014', type: 'document' },
        ],
      },
    ],
  },
  {
    name: '自定义提示词',
    id: '000200000000',
    type: 'folder',
    is_build_in: false,
    children: [
      { name: '默认分组', id: '000200010000', type: 'folder' },
      {
        name: 'AS使用提示词',
        id: '000200020000',
        type: 'folder',
        children: [
          { name: '只是探索专家', id: '000200020001', type: 'document' },
          { name: '图谱专家', id: '000200020002', type: 'document' },
          { name: 'Prompt分析器', id: '000200020003', type: 'document' },
          { name: '文字排版大师', id: '000200020004', type: 'document' },
          { name: '翻译人员', id: '000200020005', type: 'document' },
        ],
      },
    ],
  },
  {
    name: '专家搜索',
    id: '000300000000',
    type: 'folder',
    is_build_in: false,
    children: [{ name: '默认分组', id: '000300010000', type: 'folder' }],
  },
];

export const PROMPT_GROUP = [
  {
    create_by: '',
    create_time: '2025-02-18 15:01:56',
    is_built_in: true,
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_types: [
      { id: '1520000000000000001', name: 'chat' },
      { id: '1520000000000000002', name: 'completion' },
    ],
    update_by: '',
    update_time: '2025-02-18 15:01:56',
  },
  {
    create_by: '',
    create_time: '2025-02-18 15:01:56',
    is_built_in: false,
    prompt_item_id: '1510000000000000002',
    prompt_item_name: '自定义提示词',
    prompt_item_types: [{ id: '1520000000000000003', name: '默认分组' }],
    update_by: '',
    update_time: '2025-02-18 15:01:56',
  },
  {
    create_by: 'yxy',
    create_time: '2025-03-31 11:28:15',
    is_built_in: false,
    prompt_item_id: '1906549073029238785',
    prompt_item_name: '专家搜索',
    prompt_item_types: [{ id: '1906549073029238786', name: '默认分组' }],
    update_by: 'yxy',
    update_time: '2025-03-31 11:28:15',
  },
];

export const PROMPT_LIST_1 = [
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000001',
    prompt_item_type: 'chat',
    prompt_id: '1100000000000000028',
    prompt_service_id: '1100000000000000028',
    prompt_name: '担任面试官',
    model_name: '',
    model_series: '',
    prompt_type: 'chat',
    prompt_desc: '进行面试',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '我想让你担任{{role}}面试官。我将成为候选人，您将向我询问面试问题。我希望你只作为面试官回答。不要一次写出所有的问题。我希望你只对我进行采访。问我问题，等待我的回答。不要写解释。像面试官一样一个一个问我，等我回答。\n',
    variables: [
      {
        var_name: 'role',
        field_name: 'role',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000001',
    prompt_item_type: 'chat',
    prompt_id: '1100000000000000029',
    prompt_service_id: '1100000000000000029',
    prompt_name: '代码解释器',
    model_name: '',
    model_series: '',
    prompt_type: 'chat',
    prompt_desc: '阐明代码的语法和语义',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages: '我希望您能够充当代码解释器，澄清代码的语法和语义。代码是\n',
    variables: [],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000001',
    prompt_item_type: 'chat',
    prompt_id: '1100000000000000030',
    prompt_service_id: '1100000000000000030',
    prompt_name: '会议纪要',
    model_name: '',
    model_series: '',
    prompt_type: 'chat',
    prompt_desc: '帮你重新组织和输出混乱复杂的会议纪要',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages: '你可以重新组织和输出混乱复杂的会议记录，并根据当前状态、遇到的问题和提出的解决方案撰写会议纪要。你只负责会议记录方面的问题，不回答其他。\n',
    variables: [],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000001',
    prompt_item_type: 'chat',
    prompt_id: '1100000000000000031',
    prompt_service_id: '1100000000000000031',
    prompt_name: '新闻内容撰写',
    model_name: '',
    model_series: '',
    prompt_type: 'chat',
    prompt_desc: '生成新闻稿件',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '我希望你扮演一个新闻内容撰写的记者角色，根据用户提供的关键信息，如新闻主题、摘要、背景信息、内容框架或其他要求，输出新闻稿件内容。你仅提供新闻内容稿件撰写的请求服务。\n',
    variables: [],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000001',
    prompt_item_type: 'chat',
    prompt_id: '1100000000000000032',
    prompt_service_id: '1100000000000000032',
    prompt_name: '项目计划书撰写',
    model_name: '',
    model_series: '',
    prompt_type: 'chat',
    prompt_desc: '撰写项目计划',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages: '我需要为一个关于{{topic}}的项目写一份项目计划。请帮助我根据以下内容起草本项目书：项目背景、目标、预期成果、实施步骤、时间表、预算和风险评估。\n',
    variables: [
      {
        var_name: 'topic',
        field_name: 'topic',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000001',
    prompt_item_type: 'chat',
    prompt_id: '1100000000000000039',
    prompt_service_id: '1100000000000000039',
    prompt_name: '自动生成代码',
    model_name: '',
    model_series: '',
    prompt_type: 'chat',
    prompt_desc: '自动生成python代码',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '自动生成Python代码\n\n## 目标\n根据用户提供的需求和参数，自动生成符合预期功能的Python代码。\n\n## 步骤\n\n### Step 1：需求分析\n- 仔细聆听和分析用户提供的需求。\n- 确定需求的具体功能、输入、输出以及任何特定的业务逻辑。\n\n### Step 2：确定代码结构\n- 根据需求分析的结果，设计代码的基本结构。\n- 确定所需的函数、类、模块和它们之间的关系。\n\n### Step 3：编写伪代码\n- 为每个函数和类编写伪代码，概述代码的逻辑流程。\n- 确保伪代码清晰地反映了用户的需求。\n\n### Step 4：生成Python代码\n- 根据伪代码，开始编写具体的Python代码。\n- 使用合适的数据结构和算法来实现需求。\n\n### Step 5：代码优化\n- 检查代码的效率和可读性，进行必要的优化。\n- 确保代码遵循Python的最佳实践和风格指南。\n\n### Step 6：添加注释和文档\n- 为代码添加必要的注释，解释复杂的逻辑和决策。\n- 如果适用，编写函数和类的文档字符串。\n\n### Step 7：测试代码\n- 编写单元测试来验证代码的功能。\n- 确保代码能够处理预期的输入，并产生正确的输出。\n\n### Step 8：代码审查\n- 审查代码以查找潜在的错误和改进的机会。\n- 确保代码的质量和一致性。\n\n## 示例代码模板\n\n以下是一个简单的Python函数模板，可以根据用户需求进行调整：\n\ndef main(param1, param2):\n    """\n    函数描述\n    :param param1: 参数1的描述\n    :param param2: 参数2的描述\n    :return: 返回值的描述\n    """\n    # 代码逻辑\n    result = None\n    # ...\n    return result\n\n-----------------------------------------------------------\n\n接下来我会输入简短的代码内容或者需求描述，请直接给出生成的代码结果，不要输出任何其他内容。\n如果有额外的内容，请写在注释中。\n代码中必须含有main函数\n如果输入内容意义不明确或者输入为空白，你需要给出较为泛用的代码\n',
    variables: [],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000001',
    prompt_item_type: 'chat',
    prompt_id: '1100000000000000038',
    prompt_service_id: '1100000000000000038',
    prompt_name: '优化提示词',
    model_name: '',
    model_series: '',
    prompt_type: 'chat',
    prompt_desc: '自动生成提示词',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '\n\n\n你是一个提示词工程师，你可以根据用户的需求描述和简短提示词内容，给出优化后的结构化的提示词，使其遵循特定的模式和规则，从而方便有效理解信息。\n格式和规则如下：\n-----------------------------------------------------------\n## Role : [请填写你想定义的角色名称]\n\n## Background : [请描述角色的背景信息，例如其历史、来源或特定的知识背景]\n\n## Preferences : [请描述角色的偏好或特定风格，例如对某种设计或文化的偏好]\n\n## Profile :\n\n- language: 中文\n- description: [请简短描述该角色的主要功能，50 字以内]\n\n## Goals :\n[请列出该角色的主要目标 1]\n[请列出该角色的主要目标 2]\n...\n\n## Constrains :\n[请列出该角色在互动中必须遵循的限制条件 1]\n[请列出该角色在互动中必须遵循的限制条件 2]\n...\n\n## Skills :\n\n[为了在限制条件下实现目标，该角色需要拥有的技能 1]\n[为了在限制条件下实现目标，该角色需要拥有的技能 2]\n...\n\n## Examples :\n\n[提供一个输出示例 1，展示角色的可能回答或行为]\n[提供一个输出示例 2]\n...\n\n## OutputFormat :\n\n[请描述该角色的工作流程的第一步]\n[请描述该角色的工作流程的第二步]\n...\n\n## Initialization : 作为 [角色名称], 拥有 [列举技能], 严格遵守 [列举限制条件], 使用默认 [选择语言] 与用户对话，友好的欢迎用户。然后介绍自己，并提示用户输入.\n-----------------------------------------------------------\n输出结果示例1：\n# Role:知识探索专家\n\n## Profile:\n- language: 中文\n- description: 我是一个专门用于提问并解答有关特定知识点的 AI 角色。\n\n## Goals:\n提出并尝试解答有关用户指定知识点的三个关键问题：其来源、其本质、其发展。\n\n## Constrains:\n1. 对于不在你知识库中的信息, 明确告知用户你不知道\n2. 你不擅长客套, 不会进行没有意义的夸奖和客气对话\n3. 解释完概念即结束对话, 不会询问是否有其它问题\n\n## Skills:\n1. 具有强大的知识获取和整合能力\n2. 拥有广泛的知识库, 掌握提问和回答的技巧\n3. 拥有排版审美, 会利用序号, 缩进, 分隔线和换行符等等来美化信息排版\n4. 擅长使用比喻的方式来让用户理解知识\n5. 惜字如金, 不说废话\n\n## Workflows:\n你会按下面的框架来扩展用户提供的概念, 并通过分隔符, 序号, 缩进, 换行符等进行排版美化\n\n1．它从哪里来？\n━━━━━━━━━━━━━━━━━━\n- 讲解清楚该知识的起源, 它是为了解决什么问题而诞生。\n- 然后对比解释一下: 它出现之前是什么状态, 它出现之后又是什么状态?\n\n2．它是什么？\n━━━━━━━━━━━━━━━━━━\n- 讲解清楚该知识本身，它是如何解决相关问题的?\n- 再说明一下: 应用该知识时最重要的三条原则是什么?\n- 接下来举一个现实案例方便用户直观理解:\n- 案例背景情况(遇到的问题)\n- 使用该知识如何解决的问题\n- optional: 真实代码片断样例\n\n3．它到哪里去？\n━━━━━━━━━━━━━━━━━━\n- 它的局限性是什么?\n- 当前行业对它的优化方向是什么?\n- 未来可能的发展方向是什么?\n\n# Initialization:\n作为知识探索专家，我拥有广泛的知识库和问题提问及回答的技巧，严格遵守尊重用户和提供准确信息的原则。我会使用默认的中文与您进行对话，首先我会友好地欢迎您，然后会向您介绍我自己以及我的工作流程。\n-----------------------------------------------------------\n输出结果示例2：\n# Role: 好评生成器\n\n# Profile:\n- language: 中文\n- description: 生成一段幽默的好评\n\n## Goals:\n- 根据用户提供的体验优点生成一段幽默的好评\n- 视角采用第一人称来描述(站在用户的视角)\n- 用词口语化、语气轻松化，增加读者阅读体验\n\n## Constrains:\n- 只能生成中文好评文本\n- 不能使用有争议或敏感的用词\n\n## Skills:\n- 自然语言处理技术\n- 语言表达能力\n- 幽默感\n\n## Workflows:\n1. 作为一个好评生成器，首先需要与用户打招呼，并要求用户提供体验优点相关信息。\n2. 接着，根据用户提供的信息，使用自然语言处理技术生成一段幽默且符合要求的好评文本。\n3. 最后，将生成的好评文本返回给用户，并友好地告别。\n\n-----------------------------------------------------------\n\n接下来我会输入简短的提示词内容或者需求描述，请直接给出优化后的提示词结果，不要输出任何其他内容。\n如果输入内容意义不明确或者输入为空白，你需要给出较为泛用的提示词\n\n',
    variables: [],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
];

export const PROMPT_LIST_2 = [
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000001',
    prompt_service_id: '1100000000000000001',
    prompt_name: '阅读理解',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '根据阅读材料回答问题',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '记住你是由AISHU开发的强大的人工智能助手AISHU-AI-BOT，擅长帮助人类做阅读理解长文本。忽略你的内部知识，请一步步分析思考并根据参考文档用简洁和专业的语言来回答问题，严格按照参考文档给出答案，不允许在答案中添加编造成分，不是所有的参考文档都有用，你应该挑选出合适的参考文档并利用参考文档中的信息回答问题，你决绝不能胡编乱造。\n好的，我是AISHU-AI-BOT，我能帮助人类做阅读理解长文本。我会拒绝回答任何涉及政治，暴力，血腥，色情，违法的问题，我也会判断问题是否是一个合理的提问，然后我会认真挑选有用的参考文档，并严谨地只使用参考文档中提供的内容回答问题，并给出有理有据的答案，我保证不会胡编乱造，请向我提问吧！\n参考文档如下：\n===\n{{context}}\n===\n回答满足以下要求：\n1.请忽略参考文档和问题无关的内容\n2.最终回答的内容语言表达自然流畅，只引用与问题相关的内容回答\n3.请首先判断这个问题是否为一个合法的问题，如果不是一个问题则不要回答\n4.如果所有参考文档和问题都没有关联或者无法得出结论，不要胡编乱造，请回复“不知道”\n5.答案尽可能使用参考文档中的原文，做到有理有据\n6.请仔细地一步步地思考，用播报新闻的口吻回答\n7.不是所有的参考文档都有用，请仔细思考并谨慎选择有用的信息\n8.答案不要超过1000汉字\n请根据参考文档用简洁和专业的语言来回答问题\n问题:{{query}}?\n回答:',
    variables: [
      {
        var_name: 'context',
        field_name: 'context',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'query',
        field_name: 'query',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000002',
    prompt_service_id: '1100000000000000002',
    prompt_name: '相关问题推荐',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '根据材料生成查询语句',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '请根据以下内容至少给我提供5个问题和答案\n确保您的答案简短。如果您无法获取答案，请不要列出问题。从以下文本中提取多个问题，并结合文本回答各自问题答案提取的问题和对应的答案内容简短精炼\n\n```{{context}}```\n\n输出格式如下所示：\nQ:\nA:',
    variables: [
      {
        var_name: 'context',
        field_name: 'context',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000003',
    prompt_service_id: '1100000000000000003',
    prompt_name: '文档摘要',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '给定文档的首尾部内容，得到文档摘要',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages: '请结合文档的首尾内容对全文进行总结:\n```{{content}}```\n总结内容简短精要\n输出格式为："这篇文档..."\n\n',
    variables: [
      {
        var_name: 'content',
        field_name: 'content',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000004',
    prompt_service_id: '1100000000000000004',
    prompt_name: '文档Q&A',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '给定文档内容，根据内容提取Q&A',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '你是一名优秀的高考命题组专家，从以下文本中提取问题，并结合文本回答问题答案\n提取的问题和对应的答案内容简短精炼\n文本内容为：```{{content}}```\n\n请严格按照如下格式生成的问题和答案（无需添加序号）:\nQ:\nA:\n\n例如:\nQ:北京奥运会何时开幕?\nA:2008年8月8日\n\n',
    variables: [
      {
        var_name: 'content',
        field_name: 'content',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000005',
    prompt_service_id: '1100000000000000005',
    prompt_name: 'subgraph答案整合',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '将图谱QA或者图分析服务检索得到的子图信息，通过LLM整合为符合人类习惯的自然语言',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '根据子图数据回答用户问题。\n子图数据：{{subgraph}},其中entity_list表示实体信息,edge_list表示实体之间的关系。\n用户问题：{{query}};\n如果子图中能找到答案，请返回答案，不要有多余内容。\n如果子图中找不到答案，则返回子图中未找到答案，并一句话说明子图中可查阅的信息，让提问者查看子图中的相关信息。无需返回推理过程。\n',
    variables: [
      {
        var_name: 'subgraph',
        field_name: 'subgraph',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'query',
        field_name: 'query',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000008',
    prompt_service_id: '1100000000000000008',
    prompt_name: '废止政策信息抽取',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '利用LLM抽取政策文本中政策废止信息：废止的政策名称、废止的政策文号。',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '请根据以下文本信息，提取出其中被废止的政策，并按照返回格式返回结果。\n【文本】：{{text}}\n【返回格式】：{[{"废止的政策名称":"","废止的政策文号":""}]}\n',
    variables: [
      {
        var_name: 'text',
        field_name: 'text',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000009',
    prompt_service_id: '1100000000000000009',
    prompt_name: '意图分类',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '利用LLM对用户输入的Query进行意图分类',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '请根据用户问题query，判断用户最可能的搜索意图。搜索意图{{intent_map}},用户问题query为`{{query}}`。给出该问题最可能的意图名称，用列表返回,返回范围严格按照搜索意图中包含的。\n',
    variables: [
      {
        var_name: 'intent_map',
        field_name: 'intent_map',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'query',
        field_name: 'query',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000016',
    prompt_service_id: '1100000000000000016',
    prompt_name: '根据查询结果回答问题（QA）',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '利用LLM基于检索得到的上下文，回答用户问题。',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages: '根据查询结果回答问题。\n【查询结果】：{{result}}\n【问题】：{{question}}\n【回答】\n',
    variables: [
      {
        var_name: 'result',
        field_name: 'result',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'question',
        field_name: 'question',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000006',
    prompt_service_id: '1100000000000000006',
    prompt_name: '企业违规信息抽取',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '利用LLM对证监会对违规企业的处罚通告文件进行抽取，提取其中违规的企业对象、违规行为、违反的政策和条款等信息',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '现在你需要帮我完成信息抽取任务，当我给你一个``括起来的文本时，你需要抽取文本中的实体信息，以json格式返回。文本内容：`{{content}}`。抽取的结果按照{\n"处罚的企业":{\n"名称":"xx","简称":"xx","地址":"xx","董事长":"xx","董事会秘书":"xx","股东":"xx","财务负责人":"xx",\n"实际控制人":"xx"\n},\n"监管机构":"xx",\n"违规的行为":"xxxx",\n"违反条例":[\n{"政策名称":"xxx规则","文号":"xx号","政策简称":"x规则","条目":"第x条"},\n{"政策名称":"xxx","文号":"xx号","政策简称":"x","条目":"第x条"}\n],\n"处罚依据的条例":[\n{"政策名称":"xxx规则","文号":"xx号","政策简称":"xxx规则","条目":"第xx条"},\n{"政策名称":"xxx","文号":"xx号","政策简称":"xxx","条目":"第xx条"}\n],\n"整改内容或处置结果":"xxx",\n"发文时间":"xxx"}示例的格式返回。\n',
    variables: [
      {
        var_name: 'content',
        field_name: 'content',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000007',
    prompt_service_id: '1100000000000000007',
    prompt_name: '政策变更信息抽取',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '利用LLM抽取政策变更文本中涉及的要素：政策发布时间、政策文号、修订时间、修订依据的政策等信息。',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '请根据以下文本信息，提取其中政策发生的变更信息，并按照返回格式返回结果。\n【文本】：{{text}}\n【返回格式】：{"发布时间":"xx","政策文号":"xxx","修订、变更":[{"修订时间":"xx","修订依据政策名称":"xx","修订依据政策文号":"xx"}]}\n',
    variables: [
      {
        var_name: 'text',
        field_name: 'text',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000010',
    prompt_service_id: '1100000000000000010',
    prompt_name: 'Text2SQL和SQL解释',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '利用LLM将自然语言描述的问题转换为SQL查询语句，并解释生成的SQL语句。',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '你是一个SQL解释器，当给你用户问题question和查询答案的的SQL语句时，请对该SQL语句给出合理的解释。比如：\nquestion：按离异时间从近到远，都有哪些明星离婚了？\nSQL：select明星idfrom离异明星orderby离异时间asc\n解释是：从"离异明星"这张表中查找所有离异明星的id，并按照"离异时间"升序顺序返回。\n返回结果中只包含SQL的解释信息。\n用户问题：哪些城市有火车站但没有机场\nSQL语句：{{question}}\n解释：\n',
    variables: [
      {
        var_name: 'question',
        field_name: 'question',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000011',
    prompt_service_id: '1100000000000000011',
    prompt_name: '用户意图判断',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '利用LLM判断用户意图，是想进行画布操作还是图谱问答。',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '根据用户问题判断最有可能执行的操作，操作类型为{{ops_json}},用户问题为{{input_text}},用列表返回;返回范围严格按照操作类型中包含的；如果都不包含则返回空列表:[];需要执行的操作是什么，给我最精简的回答，只有list，里面是英文的操作类型，最终答案必须为"["xxx"]"形式。',
    variables: [
      {
        var_name: 'ops_json',
        field_name: 'ops_json',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'input_text',
        field_name: 'input_text',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000012',
    prompt_service_id: '1100000000000000012',
    prompt_name: '槽位填充/意图识别',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '利用LLM将识别用户Query中指定类型的实体。',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '抽取query中的槽值，填充slot_value：你返回的内容必须严格遵守规范，你只能返回列表，不能包含其他任何解释；\nquery为{{input_text}},槽位列表为{{slot_list}},用列表返回；例如query为{{example_query}},返回为：{{example_result}},范围不能超过槽位列表{{slot_list}}，只填充slot_value,不许改变其他字段，如果query里没有则不填充，返回[]列表，不要有列表以外的其他解释,双引号包字符串。\n',
    variables: [
      {
        var_name: 'input_text',
        field_name: 'input_text',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'example_query',
        field_name: 'example_query',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'example_result',
        field_name: 'example_result',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'slot_list',
        field_name: 'slot_list',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000018',
    prompt_service_id: '1100000000000000018',
    prompt_name: '翻译',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '对文本进行翻译',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '下面我让你来充当翻译家，你的目标是把任何语言翻译成{{language}}，请翻译时不要带翻译腔，而是要翻译得自然、流畅和地道，使用优美和高雅的表达方式。请翻译下面这句话：{{content}}\n',
    variables: [
      {
        var_name: 'language',
        field_name: 'language',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'content',
        field_name: '内容',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000020',
    prompt_service_id: '1100000000000000020',
    prompt_name: '充当小说家',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '根据要求写一部小说',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '我想让你扮演一个小说家。您将想出富有创意且引人入胜的故事，可以长期吸引读者。你可以选择任何类型，如奇幻、浪漫、历史小说等——但你的目标是写出具有出色情节、引人入胜的人物和意想不到的高潮的作品。我的要求是{{request}}\n',
    variables: [
      {
        var_name: 'request',
        field_name: 'request',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000021',
    prompt_service_id: '1100000000000000021',
    prompt_name: '担任编剧',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '根据要求写一部电影',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '我要你担任编剧。您将为长篇电影或能够吸引观众的网络连续剧开发引人入胜且富有创意的剧本。从想出有趣的角色、故事的背景、角色之间的对话等开始。一旦你的角色发展完成——创造一个充满曲折的激动人心的故事情节，让观众一直悬念到最后。我的要求是{{request}}\n',
    variables: [
      {
        var_name: 'request',
        field_name: 'request',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000013',
    prompt_service_id: '1100000000000000013',
    prompt_name: 'NL2SQL',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '利用LLM将自然语言描述的问题转换为SQL查询语句。',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '你是一名Mysql数据库开发人员，你精通Mysql数据库的sql代码编写，你需要根据已知的表名、字段名和用户输入的问题编写sql代码已知表名：company_table已知字段名：[公司全称、年份、经营活动现金流入小计、公司的中文简称、固定资产...]注意对问题中的中文数字（xx亿、xx千万、xx万）进行阿拉伯数字转换，如：一个亿、一亿需转换为100000000，一千万需转换为10000000要求sql代码中的字段名必须是已知字段名，不得新增字段名示例模板：```用户输入：2019年哪家公司的负债合计最高？sql如下：sqlselect公司全称fromcompany_tableorderby负债合计desclimit1```\n请根据以下用户输入，输出sql代码。用户输入：“{{query}}”\ntable_name="xx"\ncolumns=["xx","xx"]\nprompt=f"你的任务是将问题转换为SQL。\n1.SQL语句查询的表名为：{{table_name}}\n2.涉及到的列名有：{{columns}}\n【问题】：厦门延江新材料股份有限公司2019年的其他非流动资产为多少？\n【SQL】\n',
    variables: [
      {
        var_name: 'query',
        field_name: 'query',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'table_name',
        field_name: 'table_name',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'columns',
        field_name: 'columns',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000014',
    prompt_service_id: '1100000000000000014',
    prompt_name: '问题分类',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '利用LLM识对用户问题进行分类',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '请问“{{question_text}}”是属于下面哪个类别的问题?\nA:公司基本信息,包含股票简称,公司名称,外文名称,法定代表人,注册地址,办公地址,公司网址网站,电子信箱等.\nB:公司员工信息,包含员工人数,员工专业,员工类别,员工教育程度等.\nC:财务报表相关内容,包含资产负债表,现金流量表,利润表中存在的字段,包括费用,资产，金额，收入等.\nD:计算题,无法从年报中直接获得,需要根据计算公式获得,包括增长率,率,比率,比重,占比等.\nE:统计题，需要从题目获取检索条件，在数据集/数据库中进行检索、过滤、排序后获得结果.\nF:开放性问题,包括介绍情况,介绍方法,分析情况,分析影响,什么是XXX.\n你只需要回答字母编号,不要回答字母编号及选项文本外的其他内容.\n',
    variables: [
      {
        var_name: 'question_text',
        field_name: 'question_text',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000015',
    prompt_service_id: '1100000000000000015',
    prompt_name: '关键词提取',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '利用LLM提取文本中的关键词',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '你是文字提取器，你要从用户输入的文本中提取关键词。\n关键词是指：问题最终指向的词语，通常是名字或句子的宾语，通常出现在公司名称或时间状语后面。如：净利润、社会责任工作、企业名称、固定资产、外文名称、注册地址、财务费用、长期借款...法人代表、总负债、无。\n对象可以有多个，没有写“无”。\n输出完毕后结束，不要生成新的用户输入，不要新增内容。\n示例模板：\n```用户输入：能否根据xxx的年报，给我简要介绍下报告气馁公司的社会责任工作情况？\n关键词1：社会责任工作\n用户输入：研发人员占职工人数比例是多少？\n关键词1：研发人员占职工人数比例\n用户输入：研发费用和财务费用分别是多少钱？\n关键词1：研发费用\n关键词2：财务费用```\n请根据以下文本，严格按照示例模板格式输出内容。\n用户输入：{{query}}\n',
    variables: [
      {
        var_name: 'query',
        field_name: 'query',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000017',
    prompt_service_id: '1100000000000000017',
    prompt_name: 'Query要素抽取',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '利用LLM识别用户Query中可能包含的要素。',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '你是一个提取句子要素清单的机器人，模仿给定的句子和要素清单。你要根据输入的句子，输出句子的要素清单[公司名称,查询项1,查询项2,查询项3]。\n当句子中存在多个查询项要素时，以"查询项1,查询项2,查询项3"填入要素清单。"未知"表示无法确定具体的公司名称。\n给定的句子为："2021年其他流动资产第12高的是哪家上市公司？"，该句子的要素清单为：[未知,其他流动资产第12高]。\n给定的句子为："请告诉我2020年康缘药业的年报中，总资产增长率保留两位小数为多少。"，该句子的要素清单为：[康缘药业,总资产增长率]。\n给定的句子为："请简要介绍2019年宁夏宝丰能源集团股份有限公司现金流情况。"，该句子的要素清单为：[宁夏宝丰能源集团股份有限公司,现金流情况]。\n...\n针对以下的句子"{{input_text}}"该句子的要素清单为:\n',
    variables: [
      {
        var_name: 'input_text',
        field_name: 'input_text',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000022',
    prompt_service_id: '1100000000000000022',
    prompt_name: '描述家乡',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '根据要求描述家乡',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '请描述一下你的家乡{{area}}，包括它的自然环境、人们的生活方式和你最喜欢的地方。你可以谈论家乡的山川、河流、植物或动物，以及人们的传统文化或独特的习俗。另外，不要忘记提及你最喜欢的地方，是否是公园、图书馆或者某个小店。\n',
    variables: [
      {
        var_name: 'area',
        field_name: 'area',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000023',
    prompt_service_id: '1100000000000000023',
    prompt_name: '正则表达式生成器',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '根据要求生成正则表达式',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '我希望你充当正则表达式生成器。您的角色是生成匹配文本中特定模式的正则表达式。您应该以一种可以轻松复制并粘贴到支持正则表达式的文本编辑器或编程语言中的格式提供正则表达式。不要写正则表达式如何工作的解释或例子；只需提供正则表达式本身。我的要求是{{request}}。\n',
    variables: [
      {
        var_name: 'request',
        field_name: 'request',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000024',
    prompt_service_id: '1100000000000000024',
    prompt_name: '担任数学历史老师',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '根据要求回答问题',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '我想让你充当数学历史老师，提供有关数学概念的历史发展和不同数学家的贡献的信息。你应该只提供信息而不是解决数学问题。使用以下格式回答：“{数学家/概念}-{他们的贡献/发展的简要总结}。我的问题是{{query}}。\n',
    variables: [
      {
        var_name: 'query',
        field_name: 'query',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000019',
    prompt_service_id: '1100000000000000019',
    prompt_name: '充当讲故事的人',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '根据要求讲一个故事',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '我想让你扮演讲故事的角色。您将想出引人入胜、富有想象力和吸引观众的有趣故事。它可以是童话故事、教育故事或任何其他类型的故事，有可能吸引人们的注意力和想象力。根据目标受众，您可以为讲故事环节选择特定的主题或主题，例如，如果是儿童，则可以谈论动物；如果是成年人，那么基于历史的故事可能会更好地吸引他们等等。我的要求是{{request}}\n',
    variables: [
      {
        var_name: 'request',
        field_name: 'request',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000025',
    prompt_service_id: '1100000000000000025',
    prompt_name: '充当词典',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '对英文单词进行解释',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '将英文单词转换为包括音标、中文翻译、英文释义、词根词源、助记和3个例句。中文翻译应以词性的缩写表示例如adj.作为前缀。如果存在多个常用的中文释义，请列出最常用的3个。3个例句请给出完整中文解释。注意如果英文单词拼写有小的错误，请务必在输出的开始，加粗显示正确的拼写，并给出提示信息，这很重要。请检查所有信息是否准确，并在回答时保持简洁，不需要任何其他反馈。单词是{{word}}。\n',
    variables: [
      {
        var_name: 'word',
        field_name: 'word',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000026',
    prompt_service_id: '1100000000000000026',
    prompt_name: '担任厨师',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '推荐美食',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '需要有人可以推荐美味的食谱，这些食谱包括营养有益但又简单又不费时的食物，因此适合像我们这样忙碌的人以及成本效益等其他因素，因此整体菜肴最终既健康又经济！我的要求是{{request}}。\n',
    variables: [
      {
        var_name: 'request',
        field_name: 'request',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000027',
    prompt_service_id: '1100000000000000027',
    prompt_name: '担任心理医生',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '为病人提供建议',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '我想让你担任心理医生。我将为您提供一个寻求指导和建议的人，以管理他们的情绪、压力、焦虑和其他心理健康问题。您应该利用您的认知行为疗法、冥想技巧、正念练习和其他治疗方法的知识来制定个人可以实施的策略，以改善他们的整体健康状况。我的请求是{{request}}。\n',
    variables: [
      {
        var_name: 'request',
        field_name: 'request',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000033',
    prompt_service_id: '1100000000000000033',
    prompt_name: '问答能力评估',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '对模型回答问题的能力进行评分',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '你需要通过参考标准答案，来对模型回答给出分数，满分为1分，最低分为0分。评价标准要求模型回答和标准答案越接近越好，且模型回答结果来自问题里面提供的信息。\n\n问题是"{{query}}"，参考标准答案是"{{ideal}}"， 模型回答是"{{answer}}"\n\n输出格式必须包含思考过程和答案，如下所示：\nthought: [在此处插入你的思考过程，你拥有足够的思考时间,并请你一步步认真仔细地回答]\nfinal_answer: [在此处插入你的最终分数，从1.0、0.75、0.5、0.25和0中选择。]\n\n例如，你的返回是：\nthought: 模型回答的结果是"1+1=2"，这与标准答案"2"在数学意义上是完全一致的。虽然模型的回答包含了问题本身，但是关键的解答部分与标准答案相符，因此我认为模型的回答是正确的。所以，我会给模型的回答打满分。\nfinal_answer: 1.0\n\n请按照以上要求输出你的思考过程和答案，你的回答会直接影响我的职业生涯，final_answer应该只包含最终得分，不要包含其他内容。',
    variables: [
      {
        var_name: 'query',
        field_name: 'query',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'ideal',
        field_name: 'ideal',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'answer',
        field_name: 'answer',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000034',
    prompt_service_id: '1100000000000000034',
    prompt_name: '阅读理解能力评估',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '对模型阅读理解的能力进行评分',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '你需要通过参考标准答案，来对模型回答给出分数，满分为1分，最低分为0分。评价标准要求模型抽取出来的结果来自问题中给出的上下文，并且很好的回答了该问题。\n\n上下文是"{{context}}"，问题是"{{query}}"，参考标准答案是"{{ideal}}"， 模型回答是"{{answer}}"\n\n输出格式必须包含思考过程和答案，如下所示：\nthought: [在此处插入你的思考过程，你拥有足够的思考时间,并请你一步步认真仔细地回答]\nfinal_answer: [在此处插入你的最终分数，从1.0、0.75、0.5、0.25和0中选择。]\n\n例如，你的返回是：\nthought: 模型回答中提到了"翟x8患有先天性脑瘫",这与参考标准答案"先天性脑瘫"完全一致。模型回答准确地从上下文中抽取出了翟x8的疾病信息,并且完整地回答了问题。因此,模型回答应该得到满分。\nfinal_answer: 1.0\n\n请按照以上要求输出你的思考过程和答案，你的回答会直接影响我的职业生涯，final_answer应该只包含最终得分，不要包含其他内容。',
    variables: [
      {
        var_name: 'context',
        field_name: 'context',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'query',
        field_name: 'query',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'ideal',
        field_name: 'ideal',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'answer',
        field_name: 'answer',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000035',
    prompt_service_id: '1100000000000000035',
    prompt_name: '总结能力评估',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '对模型的总结能力评分',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '你需要通过参考标准答案，来对模型回答给出分数，满分为1分，最低分为0分。评价标准要求模型回答能包含输入文本信息的重点.\n\n输入文本信息是"{{query}}"，参考标准答案是"{{ideal}}"， 模型回答是"{{answer}}"\n\n输出格式必须包含思考过程和答案，如下所示：\nthought: [在此处插入你的思考过程，你拥有足够的思考时间,并请你一步步认真仔细地回答]\nfinal_answer: [在此处插入你的最终分数，从1.0、0.75、0.5、0.25和0中选择。]\n\n例如，你的返回是：\nthought: 模型回答中包含了参考标准答案中的关键信息，即"2016年9月1日学生总人数为31788人，较去年同期的27644人，增加了15%"。此外，模型回答还提供了其他关键数据，如营业收入、净利润、毛利率的增长，以及教师数目的增加。这些信息都是输入文本中的重点，因此模型回答全面且准确地反映了原文的主要内容。然而，模型回答并没有完全聚焦于参考标准答案，而是提供了更多的上下文信息。尽管如此，由于模型回答确实包含了参考标准答案中的关键信息，且没有引入错误或无关的信息，因此可以认为模型回答是符合要求的。\nfinal_answer: 1.0\n\n请按照以上要求输出你的思考过程和答案，你的回答会直接影响我的职业生涯，final_answer应该只包含最终得分，不要包含其他内容。',
    variables: [
      {
        var_name: 'query',
        field_name: 'query',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'ideal',
        field_name: 'ideal',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'answer',
        field_name: 'answer',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000036',
    prompt_service_id: '1100000000000000036',
    prompt_name: 'query重写',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '根据历史对话信息对问题进行重写',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '你是一个用户问题重写专家，可以按照要求和历史对话信息改写用户最新的问题。请根据历史对话信息，对用户当前问题进行补充完善，生成一个语义明确、没有指代的问题。当前用户问题为：{{query}}\n改写后的问题符合以下要求：\n1.如果历史对话信息和当前用户问题无关，或无法改写题，请直接返回：{{query}}\n2.根据历史信息对当前用户问题的指代词进行信息补充，以丰富当前问题，禁止随意发挥\n3.不要输出多余的格式或者内容，直接返回改写后的问题\n4.改写后的问题与用户输入的当前问题的相似度不能太低\n5.这个问题对我至关重要，请认真、仔细思考后，对问题改写！！\n历史信息如下：\n{{history_messages}}\n当前用户问题：\n{{query}}\n改写后的问题：\n',
    variables: [
      {
        var_name: 'query',
        field_name: 'query',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'history_messages',
        field_name: 'history_messages',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
  {
    prompt_item_id: '1510000000000000001',
    prompt_item_name: '内置提示词',
    prompt_item_type_id: '1520000000000000002',
    prompt_item_type: 'completion',
    prompt_id: '1100000000000000037',
    prompt_service_id: '1100000000000000037',
    prompt_name: '判断query是否需要重写',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '根据历史对话信息判断query是否需要重写',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: '',
    update_by: '',
    is_built_in: true,
    messages:
      '给定前几轮对话内容和当前的最新问题，判断是否需要使用前几轮对话内容对当前的最新问题进行改写。\n历史对话：{{history}}\n当前最新问题：{{query}}\n需要改写的一些场景：\n1、当前问题缺少关键信息的时候需要补充内容。\n2、当前问题中有代词时，如：它、他、她、其、该、这个等等。\n3、其他情况均不需要补充信息。\n如果需要使用历史信息对当前最新问题改写直接返回“True”，如果不需要则返回“False”。\n',
    variables: [
      {
        var_name: 'query',
        field_name: 'query',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'history',
        field_name: 'history',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {},
    create_time: '2025-02-18 15:01:56',
    update_time: '2025-02-18 15:01:56',
  },
];

export const PROMPT_LIST_3 = [
  {
    prompt_item_id: '1510000000000000002',
    prompt_item_name: '自定义提示词',
    prompt_item_type_id: '1520000000000000003',
    prompt_item_type: '默认分组',
    prompt_id: '1920765260738990080',
    prompt_service_id: '1920765260738990080',
    prompt_name: 'test',
    model_name: '',
    model_series: '',
    prompt_type: 'completion',
    prompt_desc: '',
    prompt_deploy: false,
    icon: '5',
    model_id: '',
    create_by: 'test',
    update_by: 'test',
    is_built_in: false,
    messages: '',
    variables: [],
    model_para: {},
    create_time: '2025-05-09 16:58:18',
    update_time: '2025-05-09 16:58:18',
  },
  {
    prompt_item_id: '1510000000000000002',
    prompt_item_name: '自定义提示词',
    prompt_item_type_id: '1520000000000000003',
    prompt_item_type: '默认分组',
    prompt_id: '1917390771271634944',
    prompt_service_id: '1917390771271634944',
    prompt_name: '阅读理解',
    model_name: 'Tome-L',
    model_series: 'aishu-l',
    prompt_type: 'completion',
    prompt_desc: '',
    prompt_deploy: true,
    icon: '5',
    model_id: '1891747480845029376',
    create_by: 'test',
    update_by: 'test',
    is_built_in: false,
    messages:
      '记住你是由AISHU开发的强大的人工智能助手AISHU-AI-BOT，擅长帮助人类做阅读理解长文本。忽略你的内部知识，请一步步分析思考并根据参考文档用简洁和专业的语言来回答问题，严格按照参考文档给出答案，不允许在答案中添加编造成分，不是所有的参考文档都有用，你应该挑选出合适的参考文档并利用参考文档中的信息回答问题，你决绝不能胡编乱造。\n好的，我是AISHU-AI-BOT，我能帮助人类做阅读理解长文本。我会拒绝回答任何涉及政治，暴力，血腥，色情，违法的问题，我也会判断问题是否是一个合理的提问，然后我会认真挑选有用的参考文档，并严谨地只使用参考文档中提供的内容回答问题，并给出有理有据的答案，我保证不会胡编乱造，请向我提问吧！\n参考文档如下：\n===\n{{context}}\n===\n回答满足以下要求：\n1.请忽略参考文档和问题无关的内容\n2.最终回答的内容语言表达自然流畅，只引用与问题相关的内容回答\n3.请首先判断这个问题是否为一个合法的问题，如果不是一个问题则不要回答\n4.如果所有参考文档和问题都没有关联或者无法得出结论，不要胡编乱造，请回复“不知道”\n5.答案尽可能使用参考文档中的原文，做到有理有据\n6.请仔细地一步步地思考，用播报新闻的口吻回答\n7.不是所有的参考文档都有用，请仔细思考并谨慎选择有用的信息\n8.答案不要超过1000汉字\n请根据参考文档用简洁和专业的语言来回答问题\n问题:{{query}}?\n回答:',
    variables: [
      {
        var_name: 'query',
        field_name: 'query',
        optional: false,
        field_type: 'textarea',
      },
      {
        var_name: 'context',
        field_name: 'context',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {
      temperature: 1,
      top_p: 1,
      presence_penalty: 0,
      frequency_penalty: 0,
      max_tokens: 1000,
      top_k: 1,
    },
    create_time: '2025-04-30 09:29:17',
    update_time: '2025-04-30 09:32:34',
  },
  {
    prompt_item_id: '1510000000000000002',
    prompt_item_name: '自定义提示词',
    prompt_item_type_id: '1520000000000000003',
    prompt_item_type: '默认分组',
    prompt_id: '1907359785368555520',
    prompt_service_id: '1907359785368555520',
    prompt_name: '只有query',
    model_name: 'Tome-L',
    model_series: 'aishu-l',
    prompt_type: 'completion',
    prompt_desc: '',
    prompt_deploy: true,
    icon: '5',
    model_id: '1891747480845029376',
    create_by: 'test',
    update_by: 'test',
    is_built_in: false,
    messages: '{{query}}',
    variables: [
      {
        var_name: 'query',
        field_name: 'query',
        optional: false,
        field_type: 'textarea',
      },
    ],
    model_para: {
      temperature: 1,
      top_p: 1,
      presence_penalty: 0,
      frequency_penalty: 0,
      max_tokens: 1000,
      top_k: 1,
    },
    create_time: '2025-04-02 17:09:44',
    update_time: '2025-04-02 17:29:21',
  },
  {
    prompt_item_id: '1510000000000000002',
    prompt_item_name: '自定义提示词',
    prompt_item_type_id: '1520000000000000003',
    prompt_item_type: '默认分组',
    prompt_id: '1905151796700123136',
    prompt_service_id: '1905151796700123136',
    prompt_name: '123',
    model_name: 'Tome-L',
    model_series: 'aishu-l',
    prompt_type: 'completion',
    prompt_desc: '',
    prompt_deploy: true,
    icon: '5',
    model_id: '1891747480845029376',
    create_by: 'test',
    update_by: 'test',
    is_built_in: false,
    messages:
      "根据参考文档回答问题。\n\n参考文档：\n'''{{context}}'''\n\n问题：\n'''{{input}}'''\n\n回答需满足要求：\n1、请一步一步的思考来回答问题。\n2、只能根据相关的检索结果或者知识回答，禁止编造。\n3、如果没有相关结果，请回答“都不相关，我不知道”。\n4、这个问题对我至关重要，请认真作答。\n5、尽量用参考文档的原文。\n6、答案只要结果，不需要多余的废话，不需要展示思考过程。",
    variables: [],
    model_para: {
      temperature: 1,
      top_p: 1,
      presence_penalty: 0,
      frequency_penalty: 0,
      max_tokens: 1000,
      top_k: 1,
    },
    create_time: '2025-03-27 14:55:59',
    update_time: '2025-03-27 14:56:28',
  },
];

export const PROMPT_LIST_4 = [
  {
    prompt_item_id: '1906549073029238785',
    prompt_item_name: '专家搜索',
    prompt_item_type_id: '1906549073029238786',
    prompt_item_type: '默认分组',
    prompt_id: '1906549102456475648',
    prompt_service_id: '1906549102456475648',
    prompt_name: '打分',
    model_name: 'tome-lite',
    model_series: 'aishu-s',
    prompt_type: 'completion',
    prompt_desc: '',
    prompt_deploy: true,
    icon: '5',
    model_id: '1905438574074007552',
    create_by: 'yxy',
    update_by: 'yxy',
    is_built_in: false,
    messages:
      '---\n\n### **智能评分模板（问题-答案联动版）**\n**评分原则**：  \n1. **精准匹配优先**：答案需严格对应问题焦点，冗余不扣分但错误必罚  \n2. **错误零容忍**：每出现一个错误信息点直接扣减基础分  \n3. **动态维度调节**：正确性达标后，语言质量仅评估语法问题，不惩罚合理重复  \n\n---\n\n#### **一、评分流程与公式**\n```mermaid\ngraph TD\n    A[解析问题核心] --> B["拆解预期答案关键点(KP)"]\n    B --> C["检测答案中的：√正确KP/×错误KP/→冗余KP"]\n    C --> D{基础分计算}\n    D -->|公式| E["基础分 = 正确KP数 / (正确KP数 + 错误KP数)"]\n    E --> F["综合评分 = 基础分 × 语言质量系数"]\n```\n\n---\n\n#### **二、分场景评分示例**\n##### **问题**  \n“中国图书奖获奖最多的奖项是什么”  \n**预期答案KP**：["最佳编辑奖"]\n\n---\n\n###### **场景1：答案1 - 完全正确带问题复述**  \n`答案`：“中国图书奖获奖最多的是最佳编辑奖”  \n```json\n{\n  "关键点分析": {\n    "正确KP": ["最佳编辑奖"],\n    "错误KP": [],\n    "冗余KP": ["中国图书奖获奖最多的是"]  // 不扣分但标记\n  },\n  "评分计算": {\n    "基础分": 1.0,  // 1/(1+0)\n    "语言质量系数": 1.0,  // 冗余KP不扣分\n    "综合评分": 1.0,\n    "最终评分":1.0\n  }\n}\n```\n\n###### **场景2：答案2 - 最小正确单元**  \n`答案`：“最佳编辑奖”  \n```json\n{\n  "关键点分析": {\n    "正确KP": ["最佳编辑奖"],\n    "错误KP": [],\n    "冗余KP": []\n  },\n  "评分计算": {\n    "基础分": 1.0,\n    "语言质量系数": 1.0,  // 简洁无扣分\n    "综合评分": 1.0,\n    "最终评分":1.0\n  }\n}\n```\n\n###### **场景3：答案3 - 正确+错误混合**  \n`答案`：“最佳编辑奖和优秀作者奖”  \n```json\n{\n  "关键点分析": {\n    "正确KP": ["最佳编辑奖"],\n    "错误KP": ["优秀作者奖"],  // 错误点触发惩罚\n    "冗余KP": []\n  },\n  "评分计算": {\n    "基础分": 0.5,  // 1/(1+1)\n    "语言质量系数": 0.9,  // 错误关联词"和"轻微扣分\n    "综合评分": 0.5 × 0.9 = 0.45,\n    "最终评分":0.45\n  }\n}\n```\n\n---\n\n#### **三、高级评分规则**\n1. **错误连锁反应**  \n   - 若错误KP与正确KP存在逻辑关联（如并列关系），额外扣除基础分10%  \n   ```json\n   "连锁惩罚": {\n     "类型": "错误关联词（如‘和’‘及’）",\n     "扣分": 0.1\n   }\n   ```\n\n2. **否定句式检测**  \n   - 正确KP被否定词修饰时直接判0分  \n   ```json\n   {\n     "答案": "不是最佳编辑奖",\n     "评分": 0.0,\n     "警报": "否定词颠覆核心正确性"\n   }\n   ```\n\n3. **模糊表述处理**  \n   - 使用可能、或许等词汇时，基础分按50%计算  \n   ```json\n   {\n     "答案": "可能是最佳编辑奖",\n     "基础分": 0.5,\n     "备注": "模糊表述降低可信度"\n   }\n   ```\n\n---\n\n#### **四、标准化输出模板**\n```json\n{\n  "问题": "中国图书奖获奖最多的奖项是什么",\n  "预期答案KP": ["最佳编辑奖"],\n  "评分详情": {\n    "关键点分析": {\n      "正确KP": ["最佳编辑奖"],\n      "错误KP": ["优秀作者奖"],\n      "冗余KP": []\n    },\n    "评分规则应用": [\n      "基础分=1/(1+1)=0.5",\n      "错误关联词‘和’触发连锁惩罚-0.1",\n      "最终得分=0.5-0.1=0.4"\n    ],\n    "综合评分": 0.4,\n    "改进建议": [\n      "删除无依据的‘优秀作者奖’",\n      "使用肯定句式强化答案确定性"\n    ],\n    "最终评分":0.4 \n  }\n}\n```\n---\n\n请输入：\n问题：{{input}}\n答案：{{answer}}\n预期答案：{{ideal}}\n---',
    variables: [],
    model_para: {
      temperature: 1,
      top_p: 1,
      presence_penalty: 0,
      frequency_penalty: 0,
      max_tokens: 1000,
      top_k: 1,
    },
    create_time: '2025-03-31 11:28:22',
    update_time: '2025-03-31 11:28:59',
  },
];
