apiVersion: v2
name: proton-mariadb
description: A Helm chart for MariaDB single-node deployment
type: application
version: 1.0.0
appVersion: "11.4"
keywords:
  - mariadb
  - database
  - sql
maintainers:
  - name: Proton
    email: support@proton.com
