use af_data_catalog;

CREATE TABLE IF NOT EXISTS `t_target` (
    `id` BIGINT  NOT NULL AUTO_INCREMENT COMMENT '唯一ID，雪花算法',
    `target_name` VARCHAR(100) NOT NULL COMMENT '目标名称',
    `target_type` TINYINT NOT NULL DEFAULT 1 COMMENT '目标类型：1=部门目标，2=个人目标',
    `department_id` CHAR(36) NOT NULL COMMENT '责任部门ID',
    `description` TEXT COMMENT '目标描述',
    `start_date` DATE NOT NULL COMMENT '开始日期',
    `end_date` DATE NULL COMMENT '结束日期',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1=未到期，2=待评价，3=已结束',
    `responsible_uid` char(36) NOT NULL COMMENT '责任人ID',
    `employee_id` char(36) NOT NULL COMMENT '协助成员ID,多个用逗号分隔',
    `evaluation_content` text COMMENT '整体评价内容',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `created_by` char(36) NOT NULL COMMENT '创建人',
    `updated_at` DATETIME(3) DEFAULT NULL comment '更新时间',
    `updated_by` char(36) DEFAULT NULL COMMENT '更新人',
    PRIMARY KEY (`id`),
    INDEX idx_department_id (department_id),
    INDEX idx_start_end_date (start_date, end_date),
    INDEX idx_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='考核目标表';

CREATE TABLE IF NOT EXISTS `t_target_plan` (
     `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '唯一ID，雪花算法',
     `target_id` bigint(20) NOT NULL COMMENT '所属目标ID',
     `plan_type` tinyint(4) NOT NULL COMMENT '考核计划类型：1=数据获取，2=数据质量整改，3=数据资源编目，4=业务梳理,5=数据处理,6=数据理解',
     `plan_name` varchar(100) NOT NULL COMMENT '计划名称',
     `plan_desc` text null COMMENT '计划描述',
     `responsible_uid` varchar(50) NOT NULL COMMENT '责任人用户ID',
     `plan_quantity` int(11) NOT NULL COMMENT '计划数量（如：计划归集资源数量）',
     `actual_quantity` int(11) DEFAULT NULL COMMENT '实际完成数量（如：已归集资源数量）',
     `status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '状态：0=未填，1=已填，2=异常',
     `related_data_collection_plan_id` text null COMMENT '关联的数据归集计划ID',
     `related_data_collection_plan_name` varchar(255) DEFAULT NULL COMMENT '关联数据归集计划名称',
     `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3) COMMENT '创建时间',
     `created_by` char(36) NOT NULL COMMENT '创建人',
     `updated_at` datetime(3) DEFAULT NULL COMMENT '更新时间',
     `updated_by` char(36) DEFAULT NULL COMMENT '更新人',
     `business_model_quantity` int(11) DEFAULT NULL COMMENT '计划构建业务模型数量',
     `business_process_quantity` int(11) DEFAULT NULL COMMENT '计划梳理业务流程数量',
     `business_table_quantity` int(11) DEFAULT NULL COMMENT '计划设计业务表数量',
     `business_model_actual_quantity` int(11) DEFAULT NULL COMMENT '实际构建业务模型数量',
     `business_process_actual_quantity` int(11) DEFAULT NULL COMMENT '实际梳理业务流程数量',
     `business_table_actual_quantity` int(11) DEFAULT NULL COMMENT '实际设计业务表数量',
     `data_process_explore_quantity` int(11) DEFAULT NULL COMMENT '计划探查表数量（数据处理类型）',
     `data_process_fusion_quantity` int(11) DEFAULT NULL COMMENT '计划融合表数量（数据处理类型）',
     `data_process_explore_actual_quantity` int(11) DEFAULT NULL COMMENT '实际探查表数量（数据处理类型）',
     `data_process_fusion_actual_quantity` int(11) DEFAULT NULL COMMENT '实际融合表数量（数据处理类型）',
     `data_understanding_quantity` int(11) DEFAULT NULL COMMENT '计划理解数据资源目录数量（数据理解类型）',
     `data_understanding_actual_quantity` int(11) DEFAULT NULL COMMENT '实际理解数据资源目录数量（数据理解类型）',
     `related_data_process_plan_id` text null COMMENT '关联的数据处理计划ID（运营考核类型）',
     `related_data_understanding_plan_id` text null COMMENT '关联的数据理解计划ID（运营考核类型）',
     `data_collection_quantity` int(11) DEFAULT NULL COMMENT '计划归集资源数量（运营考核-数据获取类型）',
     `data_collection_actual_quantity` int(11) DEFAULT NULL COMMENT '实际归集资源数量（运营考核-数据获取类型）',
     `assessment_type` tinyint(2) DEFAULT NULL COMMENT '类别：1-部门考核  2-运营考核',
     PRIMARY KEY (`id`),
     KEY `idx_target_id` (`target_id`),
     KEY `idx_plan_type` (`plan_type`),
     KEY `idx_responsible_uid` (`responsible_uid`),
     KEY `idx_status` (`status`),
     KEY `idx_plan_quantity` (`plan_quantity`),
     CONSTRAINT `t_target_plan_ibfk_1` FOREIGN KEY (`target_id`) REFERENCES `t_target` (`id`) ON DELETE CASCADE
     ) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='考核计划表（含详情与评价）';
