apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proton-mariadb.fullname" . }}-auth
  namespace: {{ .Values.mariadb.namespace }}
  labels:
    {{- include "proton-mariadb.labels" . | nindent 4 }}
type: Opaque
stringData:
  mariadb-root-password: {{ .Values.mariadb.auth.rootPassword | quote }}
  mariadb-database: {{ .Values.mariadb.auth.database | quote }}
  mariadb-user: {{ .Values.mariadb.auth.username | quote }}
  mariadb-password: {{ .Values.mariadb.auth.password | quote }}
