apiVersion: v1
kind: Service
metadata:
  name: {{ include "proton-mariadb.fullname" . }}
  namespace: {{ .Values.mariadb.namespace }}
  labels:
    {{- include "proton-mariadb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "proton-mariadb.selectorLabels" . | nindent 4 }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "proton-mariadb.fullname" . }}-headless
  namespace: {{ .Values.mariadb.namespace }}
  labels:
    {{- include "proton-mariadb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "proton-mariadb.selectorLabels" . | nindent 4 }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
