USE af_tasks;

CREATE TABLE IF NOT EXISTS `data_comprehension_plan` (
   `data_comprehension_plan_id` bigint(20) unsigned NOT NULL COMMENT '雪花id',
   `id` char(36) NOT NULL COMMENT '对象id，uuid',
   `name` varchar(128) NOT NULL COMMENT '名称',
   `responsible_uid` char(36) NOT NULL COMMENT '责任人id',
   `started_at` bigint(20) unsigned NOT NULL COMMENT '开始日期',
   `finished_at` bigint(20) unsigned DEFAULT NULL COMMENT '结束日期',
   `task_id` char(36) DEFAULT NULL COMMENT '关联任务id',
   `attachment_id` char(36) DEFAULT NULL COMMENT '附件ID',
   `attachment_name` VARCHAR(255) DEFAULT NULL COMMENT '附件名称',
   `content` text  COMMENT '计划内容',
   `opinion` varchar(300) DEFAULT '' COMMENT '申报意见',
   `audit_status` tinyint(2) DEFAULT NULL COMMENT '审核状态 1:审核中 2: 已撤销 3：已驳回 4: 通过',
   `audit_id` bigint(20) DEFAULT NULL COMMENT '审核记录ID',
   `audit_proc_inst_id` VARCHAR(64) DEFAULT NULL COMMENT '审核实例ID',
   `audit_result` VARCHAR(64) DEFAULT NULL COMMENT '审核结果 agree 通过 reject 拒绝 undone 撤销',
   `reject_reason` VARCHAR(300) DEFAULT NULL COMMENT '驳回原因',
   `cancel_reason` VARCHAR(300) DEFAULT NULL COMMENT '需求撤销原因',
   `status` tinyint(2) DEFAULT NULL COMMENT '申报状态 1:未开始 2: 进行中 3: 已完成',
   `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3) COMMENT '创建时间',
   `created_by_uid` char(36) NOT NULL COMMENT '创建用户ID',
   `updated_at` datetime(3) NOT NULL DEFAULT current_timestamp(3)  COMMENT '更新时间',
   `updated_by_uid` char(36) NOT NULL COMMENT '更新用户ID',
   `deleted_at` bigint(20) DEFAULT 0 COMMENT '删除时间(逻辑删除)',
  PRIMARY KEY (`data_comprehension_plan_id`),
  UNIQUE KEY `data_comprehension_plan_name` (`name`,`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据理解计划';

CREATE TABLE IF NOT EXISTS `data_aggregation_plan` (
   `data_aggregation_plan_id` bigint(20) unsigned NOT NULL COMMENT '雪花id',
   `id` char(36) NOT NULL COMMENT '对象id，uuid',
   `name` varchar(128) NOT NULL COMMENT '名称',
   `responsible_uid` char(36) NOT NULL COMMENT '责任人id',
   `priority` varchar(64) NOT NULL COMMENT '优先级',
   `started_at` bigint(20) unsigned NOT NULL COMMENT '开始日期',
   `finished_at` bigint(20) unsigned DEFAULT NULL COMMENT '结束日期',
   `auto_start` tinyint(4) NOT NULL COMMENT '是否自动启动，枚举：0：不自动启动 1：自动启动',
   `content`  text   COMMENT '计划内容',
   `opinion` varchar(300) DEFAULT '' COMMENT '申报意见',
   `audit_status` tinyint(2) DEFAULT NULL COMMENT '审核状态 1:审核中 2: 已撤销 3：已驳回 4: 通过',
   `audit_id` bigint(20) DEFAULT NULL COMMENT '审核记录ID',
   `audit_proc_inst_id` VARCHAR(64) DEFAULT NULL COMMENT '审核实例ID',
   `audit_result` VARCHAR(64) DEFAULT NULL COMMENT '审核结果 agree 通过 reject 拒绝 undone 撤销',
   `reject_reason` VARCHAR(300) DEFAULT NULL COMMENT '驳回原因',
   `cancel_reason` VARCHAR(300) DEFAULT NULL COMMENT '需求撤销原因',
   `status` tinyint(2) DEFAULT NULL COMMENT '申报状态 1:未开始 2: 进行中 3: 已完成',
   `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3) COMMENT '创建时间',
   `created_by_uid` char(36) NOT NULL COMMENT '创建用户ID',
   `updated_at` datetime(3) NOT NULL DEFAULT current_timestamp(3)  COMMENT '更新时间',
   `updated_by_uid` char(36) NOT NULL COMMENT '更新用户ID',
   `deleted_at` bigint(20) DEFAULT 0 COMMENT '删除时间(逻辑删除)',
  PRIMARY KEY (`data_aggregation_plan_id`),
  UNIQUE KEY `data_aggregation_plan_name` (`name`,`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据归集计划';

CREATE TABLE IF NOT EXISTS `data_processing_plan` (
   `data_processing_plan_id` bigint(20) unsigned NOT NULL COMMENT '雪花id',
   `id` char(36) NOT NULL COMMENT '对象id，uuid',
   `name` varchar(128) NOT NULL COMMENT '名称',
   `responsible_uid` char(36) NOT NULL COMMENT '责任人id',
   `priority` varchar(64) NOT NULL COMMENT '优先级',
   `started_at` bigint(20) unsigned NOT NULL COMMENT '开始日期',
   `finished_at` bigint(20) unsigned DEFAULT NULL COMMENT '结束日期',
   `content` text  COMMENT '计划内容',
   `opinion` varchar(800) DEFAULT '' COMMENT '申报意见',
   `audit_status` tinyint(2) DEFAULT NULL COMMENT '审核状态 1:审核中 2: 已撤销 3：已驳回 4: 通过',
   `audit_id` bigint(20) DEFAULT NULL COMMENT '审核记录ID',
   `audit_proc_inst_id` VARCHAR(64) DEFAULT NULL COMMENT '审核实例ID',
   `audit_result` VARCHAR(64) DEFAULT NULL COMMENT '审核结果 agree 通过 reject 拒绝 undone 撤销',
   `reject_reason` VARCHAR(300) DEFAULT NULL COMMENT '驳回原因',
   `cancel_reason` VARCHAR(300) DEFAULT NULL COMMENT '需求撤销原因',
   `status` tinyint(2) DEFAULT NULL COMMENT '申报状态 1:待申报 2：已申报',
   `created_at` datetime(3) NOT NULL DEFAULT current_timestamp(3) COMMENT '创建时间',
   `created_by_uid` char(36) NOT NULL COMMENT '创建用户ID',
   `updated_at` datetime(3) NOT NULL DEFAULT current_timestamp(3)  COMMENT '更新时间',
   `updated_by_uid` char(36) NOT NULL COMMENT '更新用户ID',
   `deleted_at` bigint(20) DEFAULT 0 COMMENT '删除时间(逻辑删除)',
  PRIMARY KEY (`data_processing_plan_id`),
  UNIQUE KEY `data_processing_plan_name` (`name`,`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据处理计划';

