USE `af_tasks`;

CREATE TABLE IF NOT EXISTS `tc_tenant_app` (
    `tenant_application_id` bigint(20) NOT NULL COMMENT '租户申请id, 雪花id',
    `id` varchar(100) DEFAULT NULL COMMENT 'id，uuid',
    `application_name` varchar(150) DEFAULT NULL COMMENT '租户申请名称',
    `application_code` varchar(100) DEFAULT NULL COMMENT '申请单编号',
    `tenant_name` varchar(150) DEFAULT NULL COMMENT '租户名称',
    `tenant_admin_id` varchar(150) DEFAULT NULL COMMENT '租户管理员',
    `business_unit_id` varchar(100) DEFAULT NULL COMMENT '业务单位id',
    `business_unit_contactor_id` varchar(100) DEFAULT NULL COMMENT '业务单位联系人',
    `business_unit_phone` varchar(150) DEFAULT NULL COMMENT '业务单位联系电话',
    `business_unit_email` varchar(150) DEFAULT NULL COMMENT '业务单位邮箱',
    `business_unit_fax` varchar(150) DEFAULT NULL COMMENT '业务单位传真',
    `maintenance_unit_id` varchar(100) DEFAULT NULL COMMENT '维护单位id',
    `maintenance_unit_name` varchar(150) DEFAULT NULL COMMENT '维护单位名称',
    `maintenance_unit_contactor_id` varchar(100) DEFAULT NULL COMMENT '维护单位联系人id',
    `maintenance_unit_contactor_name` varchar(150) DEFAULT NULL COMMENT '维护单位名称',
    `maintenance_unit_phone` varchar(150) DEFAULT NULL COMMENT '维护单位联系电话',
    `maintenance_unit_email` varchar(150) DEFAULT NULL COMMENT '维护单位邮箱',
    `status` tinyint(4) DEFAULT NULL COMMENT '状态，1 未申报， 2 待激活， 3 已激活， 4 已禁用',
    `audit_id` bigint(20) DEFAULT NULL COMMENT '审核记录ID',
    `audit_proc_inst_id` varchar(64) DEFAULT NULL COMMENT '审核实例ID',
    `audit_result` varchar(64) DEFAULT NULL COMMENT '审核结果 agree 通过 reject 拒绝 undone 撤销',
    `reject_reason` varchar(300) DEFAULT NULL COMMENT '驳回原因',
    `cancel_reason` varchar(300) DEFAULT NULL COMMENT '需求撤销原因',
    `declaration_status` tinyint(2) DEFAULT NULL COMMENT '申报状态 1:待申报 2：已申报',
    `audit_status` tinyint(4) DEFAULT NULL COMMENT '审核状态',
    `created_by_uid` varchar(36) DEFAULT NULL COMMENT '创建者id',
    `created_at` datetime DEFAULT NULL COMMENT '创建时间',
    `updated_by_uid` varchar(100) DEFAULT NULL COMMENT '更新者id',
    `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
    `deleted_at` int(11) DEFAULT 0 COMMENT '删除时间',
    PRIMARY KEY (`tenant_application_id`),
    KEY `tc_tenant_app_id_IDX` (`id`) USING BTREE,
    KEY `tc_tenant_app_tenant_application_id_IDX` (`tenant_application_id`) USING BTREE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
